### PR TITLE
Made heartBeatInterval camelCase to match the rest of the code

### PR DESCRIPTION
**Pull request by drastick**

### CODE REVIEW

**Comment by rorheden** [comment]
Heartbeat is a single word, so should for that reason not be in camel case.

**Comment by drastick** [comment]
I don't disagree, this was just the quickest fix without having to also update all the docs.

**Comment by rorheden** [comment]
Okay. We'll run through our docs and see to it that it's corrected where its wrong (i.e. heartBeat -> heartbeat). Thanks! :)

**Comment by wmbutler** [comment]
Did this get resolved?

**Pull request closed without merging**
